# SPDX-License-Identifier: GPL-2.0

CONFIG_DISABLE	= ARCH_ACTIONS ARCH_AIROHA ARCH_SUNXI ARCH_ALPINE ARCH_APPLE ARCH_BCM
CONFIG_DISABLE	+= ARCH_BERLIN ARCH_BLAIZE ARCH_EXYNOS ARCH_SPARX5 ARCH_K3 ARCH_LG1K ARCH_HISI ARCH_KEEMBAY
CONFIG_DISABLE	+= ARCH_MEDIATEK ARCH_MESON ARCH_MVEBU ARCH_NXP ARCH_LAYERSCAPE ARCH_MXC
CONFIG_DISABLE	+=  ARCH_S32 ARCH_MA35 ARCH_NPCM ARCH_REALTEK ARCH_RENESAS ARCH_ROCKCHIP
CONFIG_DISABLE	+=  ARCH_SEATTLE ARCH_INTEL_SOCFPGA ARCH_STM32 ARCH_SYNQUACER ARCH_TEGRA ARCH_TESLA_FSD
CONFIG_DISABLE	+=  ARCH_SPRD ARCH_THUNDER ARCH_THUNDER2
CONFIG_DISABLE	+=  ARCH_UNIPHIER ARCH_VEXPRESS ARCH_VISCONTI ARCH_XGENE ARCH_ZYNQMP
